version: '3.8'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - '${CONFIG}/database:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dozer']
      interval: 5s
      timeout: 5s
      retries: 5

  lavalink:
    image: fredboat/lavalink:master-v3
    environment:
      - LAVALINK_SERVER_PASSWORD

  dozer:
    image: dozer:latest
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      lavalink:
        condition: service_started
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - LAVALINK_SERVER_PASSWORD
    volumes:
      - '${CONFIG}/config:/app/config'
